#!/bin/bash
### BEGIN INIT INFO
# Provides:          motorcc
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prueba motorcc con clase.
### END INIT INFO

python3 /home/admin/PY/motorclase.py
