#!/bin/bash

### BEGIN INIT INFO
# Provides:          Rafagade16leds
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: daemon d'inici
# Description:       funcion de script para encendido de leds
### END INIT INFO

sudo python3 /home/admin/ProgramasPY/Rafagade16leds.py

