#!/bin/bash

### BEGIN INIT INFO
# Provides: Arranque_aut
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Prueba registro 74HC595 con leds.
### END INIT INFO

python3 /home/admin/Registre74HC595_Main_v2.py
